golden: add missing kernel header
Error:
hardware/u8500/display/libgralloc/hwmem_gralloc_pmem.c:40:32: fatal error: linux/android_pmem.h: No such file or directory
 #include <linux/android_pmem.h>

android_pmem.h got removed from bionic on commit https://android.googlesource.com/platform/bionic/+/be5231442b764eaee40ba7991f588d230162f739

Change-Id: I95813f83a446c80e2d1e156ed255c3038a383b6c