Update twrp-graphics.c (squashed commits)
Fixes compiling error "console.cpp:191: error: undefined reference to 'gr_maxExW'"

  Add word wrap to console output and fix scrolling in console

  Author: Dees-Troy
  Change-Id: Ibcf89952ee1391350c715f1ec82cf0cdb9b0ca7d
  https://github.com/omnirom/android_bootable_recovery/commit/1a4744a493a41b930d5a9e6f58c8d43eb3be3c42

  Disable alpha blending for non-transparent bitmaps

  * The difference isn't as big as there are not many big non-transparent
    bitmaps in TWRP, on install screen on flo it is about 5-10ms better.
    Only place where the difference is noticable is keyboard, which is
    pretty big non-transparent bitmap, where it speeds up the render
    by ~40ms on flo.

  Signed-off-by: Vojtech Bocek <vbocek@gmail.com>

  Change-Id: I4c51ef957ae2a1829ada4eb566e9964f708efcf0
  https://github.com/omnirom/android_bootable_recovery/commit/6c694b6f0bd8c6ca4552d70ee3a538d51917337e



  Disable alpha blending for fully opaque rectangles

  * This makes the rendering several times faster, because the giant
    rectangle used as background no longer uses expensive blending
    calculations, and there are also many other big rectangles which
    don't need it (fileselector, ...).

  * Results on hammerhead:
    - WITHOUT the patch - scrolling in fileselector on install page:

        I:render 67 ms, flip 6 ms, total 73 ms
        I:render 82 ms, flip 6 ms, total 88 ms
        I:render 81 ms, flip 6 ms, total 87 ms
        I:render 80 ms, flip 5 ms, total 85 ms

    - WITH the patch - scrolling in fileselector on install page:

        I:render 32 ms, flip 6 ms, total 38 ms
        I:render 16 ms, flip 6 ms, total 22 ms
        I:render 16 ms, flip 7 ms, total 23 ms
        I:render 18 ms, flip 3 ms, total 21 ms
        I:render 18 ms, flip 2 ms, total 20 ms

  * On flo, the results are even more noticable - 160ms -> 40ms

  Signed-off-by: Vojtech Bocek <vbocek@gmail.com>

  Change-Id: I5685763ba21745d7cd93133adf5f0bcb4c9a581f
  https://github.com/omnirom/android_bootable_recovery/commit/1a4744a493a41b930d5a9e6f58c8d43eb3be3c42